"""Init

Revision ID: 2cdba1a14950
Revises: 250e6c40fdc1
Create Date: 2023-10-08 14:56:23.343904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2cdba1a14950'
down_revision: Union[str, None] = '250e6c40fdc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('sam', sa.Float(), nullable=False))
    op.drop_column('payments', 'summ')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('summ', mysql.FLOAT(), nullable=False))
    op.drop_column('payments', 'sam')
    # ### end Alembic commands ###
